title: Christopher Banks
plugins_dir: ./_scripts

plugins_dir:
 - jekyll-sitemap
 - jekyll-seo-tag

collections:
  projects:
    output: true

repository: cjbanks/cjbanks.github.io
theme: minima

minima:
  skin: dark
  social_links:
          github: cjbanks
  
